version: "3.0"
services:
    broker:
      image: toke/mosquitto:latest
      volumes:
        - "./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf"
        - "./logs/broker:/mosquitto/log/"
        - "./broker/:/mosquitto/data/"
      ports:
        - "1883:1883"
    broker_log_writer:
        build: "broker_logger/."
        depends_on: 
          - broker
        volumes:
          - "./logs/subscription logs/:/logger/log"
        entrypoint: ["python3", "mqtt_client.py", "broker", "1883"]
    mini-batch-converter:
        build: "mini-batch-converter/."
        depends_on:
          - broker
        # converter.py params: broker address, broker_port, broker_name, batch_intervals, kafka_broker_address
        entrypoint: ["python3", "converter.py", "broker", "1883", "edge_1", "10", "kafka:1234"]        
